import os,time
print("正在备份到/root")
os.system("mv /etc/apt/sources.list /root")
print("添加阿里源。。。")
os.system("echo deb http://mirrors.aliyun.com/kali sana main non-free contrib >> /etc/apt/sources.list")
os.system("echo deb http://mirrors.aliyun.com/kali-security/ sana/updates main contrib non-free >> /etc/apt/sources.list")
os.system("echo deb-src http://mirrors.aliyun.com/kali-security/ sana/updates main contrib non-free >> /etc/apt/sources.list")
print("添加清华大学源。。。")
os.system("echo deb http://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling main contrib non-free >> /etc/apt/sources.list")
os.system("echo deb-src https://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling main contrib non-free >> /etc/apt/sources.list")
print("更新中。。。")
os.system("apt-get update")
os.system("apt-get upgrade")
print("现在你可以试一下用apt安装东西了，例如nginx")
print("如果没有报错且能正常安装，接下来删除root文件夹下的sources.list就能用了")
